# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Jo Vanvoorden"
author: Jo Vanvoorden

navbar-links:
  Blog: "blogposts"
  Projects: "projects"
  Resources:
#   - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
    - Emoji cheat sheet: "https://www.webfx.com/tools/emoji-cheat-sheet/"
  Tags: "tags"
  About Me: "aboutme"
#  Home sweet home: "https://ziporah.github.io"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: false

email: you-know-where-to-find-me@somewhere.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
social-network-links:
  email: "jo.vanvoorden@googlemail.com"
  github: ziporah
  twitter: JoZipke
#  linkedin:
#  patreon: DeanAttali
#  youtube: c/daattali

# If you want to show a link to an RSS in the footer, add the site description here.
# If you don't want to show an RSS link, remove the following line.
rss-description: This website is a virtual proof that I'm awesome

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: false
  vk: false

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# The keywords to associate with your website, for SEO purposes
keywords: "tech,arduino,hashicorp,terraform,devops,geek,kubernetes,raspberry,pi,k8s,microk8s,ubuntu,linux"

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#0095A1"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#0080A1"
hover-col: "#00A8A1"
footer-col: "#EAEAEA"
footer-text-col: "#666666"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

navbar-img: "/assets/img/navbar.jpg"
footer-img: "/assets/img/navbar.jpg"
#page-img: "/assets/img/bgimage.png"

# Ruby Date Format to show dates of posts
date_format: "%-d %B %Y"

# Output options (more information on Jekyll's site)
timezone: "Europe/Brussels"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 7

kramdown:
  input: GFM

collections:
  - blogposts
  - projects

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: "projects"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts-
  -
    scope:
      path: "blogposts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts-
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Build settings
# theme: minima
theme: beautiful-jekyll-theme
# theme: jekyll-theme-tactile
# theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
